### ISSUE TITLE
[BUG] team gui is not opening ( /team )

### ISSUE THREAD

**Issue by IndJitesh** [xF3d33/UltimateTeams#36] opened 2024-09-24 11:38 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**
i have typed command /team and nothing happend and that command send error on console

**Screenshots**
![image](https://github.com/user-attachments/assets/42edd621-e963-49f1-b682-68b0b91eddb5)

**Plugin version** - 2.5
The version of the plugin you are using. Latest is not a version.

**Additional context**

[11:33:23 WARN]: [UltimateTeams] Plugin UltimateTeams v2.5 generated an exception while executing task 1638
java.lang.NoClassDefFoundError: Could not initialize class dev.xf3d3.libraries.triumphteam.gui.builder.item.ItemBuilder
        at UltimateTeams-2.5.jar/dev.xf3d3.ultimateteams.menuSystem.TeamListGUI.lambda$createGui$6(TeamListGUI.java:75) ~[UltimateTeams-2.5.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.6.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Craft Scheduler Thread - 9 - UltimateTeams"]
        ... 7 more

**Comment by xF3d33** [comment] 2024-10-04 16:50
duplicate of #34

**Closed by xF3d33** 2024-10-04 16:50 UTC
